#!/bin/sh

./setup.py install --home=install

#RUNNER="valgrind python"
#RUNNER="gdb --args python"
#RUNNER="pydb --trace"
RUNNER=python
$RUNNER "-Wignore:could not open display" \
  ./yatest.py -p install/lib/python/wimpiggy \
              -p install/lib/python/xpra \
              "$@"