repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
    -   id: ruff
        args: [check, ./xpra, --ignore, E902, --ignore, E501]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=200", "--ignore=E203,E231,E225,E226,E252,E221,E741,E262,E265,E501"]

