# This file is part of Xpra.
# Copyright (C) 2026 Antoine Martin <antoine@xpra.org>
# Xpra is released under the terms of the GNU GPL v2, or, at your option, any
# later version. See the file COPYING for details.

# Map the characters a keyboard layout can produce to the X11 keysym names
# used on the wire - see `keysymdef.h`.
# Only the characters whose keysym name differs from the character itself
# are listed here: ASCII letters and digits are their own keysym name.
# Anything else falls back to the `U<codepoint>` form, as `XKeysymToString` does.

KEYSYM_NAMES: dict[str, str] = {
    # ASCII punctuation and symbols:
    ' ': 'space',
    '!': 'exclam',
    '"': 'quotedbl',
    '#': 'numbersign',
    '$': 'dollar',
    '%': 'percent',
    '&': 'ampersand',
    "'": 'apostrophe',
    '(': 'parenleft',
    ')': 'parenright',
    '*': 'asterisk',
    '+': 'plus',
    ',': 'comma',
    '-': 'minus',
    '.': 'period',
    '/': 'slash',
    ':': 'colon',
    ';': 'semicolon',
    '<': 'less',
    '=': 'equal',
    '>': 'greater',
    '?': 'question',
    '@': 'at',
    '[': 'bracketleft',
    '\\': 'backslash',
    ']': 'bracketright',
    '^': 'asciicircum',
    '_': 'underscore',
    '`': 'grave',
    '{': 'braceleft',
    '|': 'bar',
    '}': 'braceright',
    '~': 'asciitilde',
    # latin-1 supplement:
    '\xa0': 'nobreakspace',
    '¡': 'exclamdown',
    '¢': 'cent',
    '£': 'sterling',
    '¤': 'currency',
    '¥': 'yen',
    '¦': 'brokenbar',
    '§': 'section',
    '¨': 'diaeresis',
    '©': 'copyright',
    'ª': 'ordfeminine',
    '«': 'guillemotleft',
    '¬': 'notsign',
    '\xad': 'hyphen',
    '®': 'registered',
    '¯': 'macron',
    '°': 'degree',
    '±': 'plusminus',
    '²': 'twosuperior',
    '³': 'threesuperior',
    '´': 'acute',
    'µ': 'mu',
    '¶': 'paragraph',
    '·': 'periodcentered',
    '¸': 'cedilla',
    '¹': 'onesuperior',
    'º': 'masculine',
    '»': 'guillemotright',
    '¼': 'onequarter',
    '½': 'onehalf',
    '¾': 'threequarters',
    '¿': 'questiondown',
    'À': 'Agrave',
    'Á': 'Aacute',
    'Â': 'Acircumflex',
    'Ã': 'Atilde',
    'Ä': 'Adiaeresis',
    'Å': 'Aring',
    'Æ': 'AE',
    'Ç': 'Ccedilla',
    'È': 'Egrave',
    'É': 'Eacute',
    'Ê': 'Ecircumflex',
    'Ë': 'Ediaeresis',
    'Ì': 'Igrave',
    'Í': 'Iacute',
    'Î': 'Icircumflex',
    'Ï': 'Idiaeresis',
    'Ð': 'Eth',
    'Ñ': 'Ntilde',
    'Ò': 'Ograve',
    'Ó': 'Oacute',
    'Ô': 'Ocircumflex',
    'Õ': 'Otilde',
    'Ö': 'Odiaeresis',
    '×': 'multiply',
    'Ø': 'Ooblique',
    'Ù': 'Ugrave',
    'Ú': 'Uacute',
    'Û': 'Ucircumflex',
    'Ü': 'Udiaeresis',
    'Ý': 'Yacute',
    'Þ': 'Thorn',
    'ß': 'ssharp',
    'à': 'agrave',
    'á': 'aacute',
    'â': 'acircumflex',
    'ã': 'atilde',
    'ä': 'adiaeresis',
    'å': 'aring',
    'æ': 'ae',
    'ç': 'ccedilla',
    'è': 'egrave',
    'é': 'eacute',
    'ê': 'ecircumflex',
    'ë': 'ediaeresis',
    'ì': 'igrave',
    'í': 'iacute',
    'î': 'icircumflex',
    'ï': 'idiaeresis',
    'ð': 'eth',
    'ñ': 'ntilde',
    'ò': 'ograve',
    'ó': 'oacute',
    'ô': 'ocircumflex',
    'õ': 'otilde',
    'ö': 'odiaeresis',
    '÷': 'division',
    'ø': 'ooblique',
    'ù': 'ugrave',
    'ú': 'uacute',
    'û': 'ucircumflex',
    'ü': 'udiaeresis',
    'ý': 'yacute',
    'þ': 'thorn',
    'ÿ': 'ydiaeresis',
    # extras commonly found on european layouts:
    'Œ': 'OE',
    'œ': 'oe',
    'Š': 'Scaron',
    'š': 'scaron',
    'Ÿ': 'Ydiaeresis',
    'Ž': 'Zcaron',
    'ž': 'zcaron',
    'ƒ': 'function',
    '–': 'endash',
    '—': 'emdash',
    '‘': 'leftsinglequotemark',
    '’': 'rightsinglequotemark',
    '‚': 'singlelowquotemark',
    '“': 'leftdoublequotemark',
    '”': 'rightdoublequotemark',
    '„': 'doublelowquotemark',
    '†': 'dagger',
    '‡': 'doubledagger',
    '•': 'enfilledcircbullet',
    '…': 'ellipsis',
    '€': 'EuroSign',
    '™': 'trademark',
}


def keysym_name(char: str) -> str:
    """ the X11 keysym name for a character, ie: `@` is `at` """
    if not char:
        return ""
    c = char[0]
    name = KEYSYM_NAMES.get(c, "")
    if name:
        return name
    if c.isascii() and c.isalnum():
        # letters and digits are named after themselves
        return c
    return "U%04X" % ord(c)
