#!/usr/bin/env python

import sys
import signal

def addsignalhandler(sig):
    def cb(*_args):
        #print("%i\n" % sig)
        sys.exit(128+sig)
    signal.signal(sig, cb)

addsignalhandler(signal.SIGINT)
#addsignalhandler(signal.SIGSTOP)
addsignalhandler(signal.SIGTERM)
signal.pause()
