#!/usr/bin/python3

import os
import sys
import signal

def cb(*_args):
    sys.stdout.write("%s\n" % signame)
    sys.stdout.flush()
def addsignalhandler(signame, cb):
    sigval = getattr(signal, signame, None)
    if not sigval:
        return
    signal.signal(sigval, cb)

WINDOW_SIGNALS = os.environ.get("XPRA_WINDOW_SIGNALS",
                                "SIGINT,SIGTERM,SIGQUIT,SIGCONT,SIGUSR1,SIGUSR2").split(",")
for x in WINDOW_SIGNALS:
    addsignalhandler(x, cb)
def sigpipe(*_args):
	sys.exit(1)
addsignalhandler("SIGPIPE", sigpipe)
addsignalhandler("SIGHUP", sigpipe)

sys.stdin.readline()
