#!/usr/bin/env python

import sys
try:
    import xpra
    assert xpra
except ImportError as e:
    sys.stderr.write("Error: xpra for python %s is not installed\n" % (".".join(str(x) for x in sys.version_info[:2])))
    sys.exit(1)
from xpra.platform import init, set_default_name
set_default_name("Xpra")
init()

from xpra.scripts.main import main
sys.exit(main(sys.argv[0], sys.argv))
