#!/usr/bin/python3

import os
import sys

os.environ["GTK_CSD"] = "0"
from xpra.platform import program_context
with program_context("Xpra-Launcher", "Xpra Connection Launcher"):
    from xpra.client.gtk_base.client_launcher import do_main
    sys.exit(do_main(sys.argv))
