#!/bin/sh
#@PydevCodeAnalysisIgnore

function find_ld_linux {
    arch=$(uname -m)

    if [[ $arch == "x86_64" ]]; then
        if [[ -f /lib64/ld-linux-x86-64.so.2 ]]; then
            LD_LINUX='/lib64/ld-linux-x86-64.so.2'
        fi
    elif [[ $arch = "i686" ]]; then
        if [[ -f /lib/ld-linux.so.2 ]]; then
            LD_LINUX='/lib/ld-linux.so.2'
        fi
    fi

    if [[ ! $LD_LINUX ]]; then
        echo "could not determine ld_linux path, please file an xpra bug"
        exit 1
    fi
}

XORG_BIN=$(which Xorg)

if [[ -u $XORG_BIN ]]; then
    # setuid is set, we need to do magic
    find_ld_linux
    if [[ -n "$BASH" ]]; then
    	#running in bash, can show a more helpful command name:
        exec -a "Xorg-nosuid" "${LD_LINUX}" "${XORG_BIN}" "$@"
    else
        exec "${LD_LINUX}" "${XORG_BIN}" "$@"
    fi
else
    # setuid is not set on xorg_bin
    exec "${XORG_BIN}" "$@"
fi
