#!/usr/bin/env python

import sys
from xpra.platform import program_context

with program_context("Xpra-Browser", "Xpra Session Browser"):
    from xpra.client.gtk_base.sessions_gui import main
    sys.exit(main())
