#!/usr/bin/env python

import sys
import xpra.scripts.main

import pycallgraph
pycallgraph.start_trace()

x = xpra.scripts.main.main(__file__, sys.argv)

pycallgraph.make_dot_graph('pycallgraph.png')
sys.exit(x)
