.\" Man page for run_scaled
.\"
.\" Copyright (C) 2020 Antoine Martin <antoine@xpra.org>
.\"
.\" You may distribute under the terms of the GNU General Public
.\" license, either version 2 or (at your option) any later version.
.\" See the file COPYING for details.
.\"
.TH RUN_SCALED 1
.SH NAME
run_scaled - run an X11 application upscaled or downscaled
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.PD 0
.HP \w'run_scaled\ 'u
\fBrun_scaled\fP
[\fB--scale\fP=\fIVALUE\fP] application [application-arguments] [\fB--\fP] [xpra-arguments]\fB
.PD

.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBrun_scaled\fP uses \fBxpra\fP(1) to show any X11 application with arbitrary
scaling applied.

.\" --------------------------------------------------------------------
.SH EXAMPLES
.TP
\fBrun_scaled xterm -ls\fP
Starts the command "\fBxterm -ls\fP", with the default scaling of \fB2\fP.
.br
The xterm window will be twice as big as it normally would be.
.TP
\fBrun_scaled --scale=250% firefox\fP
Start firefox, upscaled by 250%.
.TP
\fBrun_scaled wine notepad.exe -- --speaker=off --microphone=off\fP
Starts the command "\fBwine notepad.exe\fP", with audio inputs and outputs disabled (by additional Xpra arguments) and the default scaling of \fB2\fP.

.\" --------------------------------------------------------------------
.SH OPTIONS

.TP
\fB--scale\fP=\fIVALUE\fP
The scaling factor to apply, specified as:
.RS
.IP \fBnumber\fP
ie: 2, 1.5
.IP \fBfraction\fP
ie: 3/2
.IP \fBpercentage\fP
ie: 250%
.RE
If unspecified, the default value is \fB2\fP.

.\" --------------------------------------------------------------------
.SH LIMITATIONS
The scaling value is limited to the range 0.1 to 10, and even within
that range, values lower than 1 may not work correctly with large
displays.

.\" --------------------------------------------------------------------
.SH SEE ALSO
\fBxpra\fP(1)
