#!/usr/bin/env python3

import sys

from xpra.platform import program_context
with program_context("Authentication", "Authentication"):
    from xpra.gtk.dialogs.auth_dialog import main
    sys.exit(main())
