.\" Man page for xpra launcher
.\"
.\" Copyright (C) 2017 Antoine Martin <antoine@devloop.org.uk>
.\"
.\" You may distribute under the terms of the GNU General Public
.\" license, either version 2 or (at your option) any later version.
.\" See the file COPYING for details.
.\"
.TH XPRA_BROWSER 1
.SH NAME
xpra_launcher \- Shows the xpra sessions found via mDNS
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.PD 0
.HP \w'xpra_launcher\ 'u
\fBxpra_launcher\fP
[\fIFILENAME\fP]\fB
.PD
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBxpra_browser\fP is a browser for \fBxpra\fP(1) sessions found via mDNS,
it allows you to easily connect to those sessions.

.\" --------------------------------------------------------------------
.SH SEE ALSO
\fBxpra\fP(1)
