#!/bin/sh

SERVER_GROUP="xpra"
if ! getent group | grep -q "^$SERVER_GROUP:" ; then
	echo -n "Adding group $SERVER_GROUP.."
	addgroup --quiet --system $SERVER_GROUP 2>/dev/null ||true
	echo "..done"
fi
