#!/bin/sh

set -e

SERVER_GROUP="xpra"
if ! getent group $SERVER_GROUP >/dev/null; then
	echo -n "Adding group $SERVER_GROUP.."
	addgroup --quiet --system $SERVER_GROUP 2>/dev/null ||true
	echo "..done"
fi
