#!/bin/sh

set -e

SERVER_GROUP="xpra"
if ! getent group $SERVER_GROUP >/dev/null; then
	echo -n "Adding group $SERVER_GROUP.."
	addgroup --quiet --system $SERVER_GROUP 2>/dev/null ||true
	echo "..done"
fi

if [ ! -f  /etc/xpra/ssl-cert.pem ]; then
	umask=`umask`
	umask 077
	openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
		-subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost" \
		-keyout "/etc/xpra/ssl-cert.pem" -out "/etc/xpra/ssl-cert.pem"
	umask $umask
fi
