#!/bin/sh

set -e

case "${1}" in
    configure)
        if ! getent group xpra >> /dev/null 2>&1; then
            addgroup --quiet --system xpra
        fi
    ;;
esac

if [ ! -f  /etc/xpra/ssl-cert.pem ]; then
	umask=`umask`
	umask 077
	openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
		-subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost" \
		-keyout "/etc/xpra/ssl-cert.pem" -out "/etc/xpra/ssl-cert.pem"
	umask $umask
fi

#DEBHELPER#
