#!/usr/bin/bash
set -e

die() { echo "$*" 1>&2 ; exit 1; }

#don't use tty prompts:
export XPRA_NOTTY=1
#don't use GUI dialogs (ie: password prompts):
export XPRA_SKIP_UI=1
export XPRA_UTIL_DEBUG=${XPRA_UTIL_DEBUG:-0}
export XPRA_TEST_DEBUG=${XPRA_TEST_DEBUG:-0}
export XPRA_HIDE_SUBPROCESS_OUTPUT=${XPRA_HIDE_SUBPROCESS_OUTPUT:-1}
export XPRA_TEST_COVERAGE=${XPRA_TEST_COVERAGE:-1}
export PYTHON=${PYTHON:-python3}
#Ubuntu will spew at too many warnings without this:
export NO_AT_BRIDGE=1
#SAVED_PYTHONPATH=$PYTHONPATH

UNITTESTS_DIR=`dirname $(readlink -f $0)`
TESTS_DIR=`dirname $UNITTESTS_DIR`
SRC_DIR=`dirname $TESTS_DIR`

PYTHON_VERSION=`$PYTHON --version | awk '{print $2}' | awk -F. '{print $1"."$2}'`

if [ -d "/usr/lib64/xpra/pkgconfig" ]; then
	EXTRA_ARGS=--pkg-config-path=/usr/lib64/xpra/pkgconfig
fi

INSTALL_PREFIX="$SRC_DIR/dist"
pushd $SRC_DIR
$PYTHON ./setup.py install --without-printing  --without-docs --with-scripts --with-cython_tracing --prefix=$INSTALL_PREFIX $EXTRA_ARGS || die "failed to build"
popd

if [ `uname` == "Linux" ]; then
	export "GDK_BACKEND=x11"
fi
export PYTHONPATH=`ls -d $INSTALL_PREFIX/lib*/python$PYTHON_VERSION/site-packages/xpra*`:.
export PATH=$INSTALL_ROOT/bin:$PATH
export XPRA_COMMAND=$INSTALL_PREFIX/bin/xpra
#undo the setuptools auto-damage:
cp $SRC_DIR/fs/bin/xpra $XPRA_COMMAND
export XPRA_CONF_DIR=$INSTALL_PREFIX/etc/xpra/

pushd $UNITTESTS_DIR
if [ "${XPRA_TEST_COVERAGE}" == "1" ]; then
	coverage erase
fi

$PYTHON ./unit/run.py "$@"

if [ "${XPRA_TEST_COVERAGE}" == "1" ]; then
	ls -la
	coverage combine
	ls -la
	coverage report -m
	ls -la
	coverage html
	[ "$GITHUB_ACTIONS" ] || xdg-open ./htmlcov/index.html
fi
popd
