#!/usr/bin/bash

die() { echo "$*" 1>&2 ; exit 1; }

export XPRA_NOTTY=1
export XPRA_UTIL_DEBUG=${XPRA_UTIL_DEBUG:-0}
export XPRA_TEST_DEBUG=${XPRA_TEST_DEBUG:-0}
export XPRA_HIDE_SUBPROCESS_OUTPUT=${XPRA_HIDE_SUBPROCESS_OUTPUT:-1}
#SAVED_PYTHONPATH=$PYTHONPATH

UNITTESTS_DIR=`dirname $(readlink -f $0)`
SRC_DIR=`dirname $UNITTESTS_DIR`

pushd $SRC_DIR
sudo python3 ./setup.py install --without-html5 --without-printing --with-scripts --without-minify --prefix=/usr || die "failed to build"
popd

if [ `uname` == "Linux" ]; then
	export "GDK_BACKEND=x11"
fi
export PYTHONPATH=.

pushd $UNITTESTS_DIR
#coverage erase
./unit/run.py "$@"

exit 0
echo "combine:"
ls -la
coverage combine
echo "report:"
ls -la
coverage report -m
echo "html:"
ls -la
coverage html
#xdg-open ./htmlcov/index.html
popd
