#!/bin/sh

#call the "Python" wrapper:
exe_name=$(basename $0)
full_path=$(cd "$(dirname "$0")"; pwd)
PYTHON="$full_path/PythonExecWrapper"

exec "$PYTHON" "GStreamer Info" -c "import sys;sys.argv[0]=\"$full_path/$exe_name\";from xpra.sound.gstreamer_util import main;main()" "$@"
