#!/bin/sh

#call the "Python" wrapper:
exe_name=$(basename $0)
#ie: APP_DIR=/Volumes/Xpra/Contents/Helpers
full_path=$(cd "$(dirname "$0")"; pwd -P)
#ie: APP_DIR=/Volumes/Xpra/Contents
CONTENTS_DIR=`dirname "$full_path"`
MANUAL="$CONTENTS_DIR/Resources/share/manual.html"

if [ -e "$MANUAL" ]; then
	open "$MANUAL"
else
	echo "Sorry, the manual page could not be found"
	echo "Opening the version found on the xpra.org website"
	open "http://xpra.org/trac/browser/xpra/trunk/src/man/xpra.1"
fi
