#!/bin/sh

#call the "PythonExecWrapper" wrapper:
exe_name=$(basename $0)
full_path=$(cd "$(dirname "$0")"; pwd)
PYTHON="$full_path/PythonExecWrapper"

exec "$PYTHON" "Python" -c "import sys;sys.argv[0]=\"$full_path/$exe_name\";from xpra.client.gl.gl_check import main;main()"
