#!/bin/sh

#call the "Python" wrapper:
exe_name=$(basename $0)
full_path=$(cd "$(dirname "$0")"; pwd)
PYTHON="$full_path/PythonExecWrapper"

exec "$PYTHON" "Xpra Launcher" -c "import sys;sys.argv[0]=\"${full_path}/$exe_name\";from xpra.client.gtk_base.client_launcher import main;main()"
