#!/bin/sh

#ie: $0=/Users/MacAdmin/Desktop/Xpra.app/Contents/MacOS/Xpra_Launcher
#ie: $0=./Xpra.app/Contents/MacOS/Xpra_Launcher
full_path=$(cd "$(dirname "$0")"; pwd)
#ie: full_path=/Users/MacAdmin/Desktop/Xpra.app/Contents/MacOS/

tmp=`dirname "$full_path"`
#ie: tmp=/Users/MacAdmin/Desktop/Xpra.app/Contents
bundle=`dirname "$tmp"`
#ie: bundle=/Users/MacAdmin/Desktop/Xpra.app
bundle_contents="$bundle"/Contents
bundle_res="$bundle_contents"/Resources
bundle_lib="$bundle_res"/lib
bundle_bin="$bundle_res"/bin
bundle_data="$bundle_res"/share
bundle_etc="$bundle_res"/etc

export DYLD_LIBRARY_PATH="$bundle_lib"
export XDG_CONFIG_DIRS="$bundle_etc"/xdg
export XDG_DATA_DIRS="$bundle_data"
export GTK_DATA_PREFIX="$bundle_res"
export GTK_EXE_PREFIX="$bundle_res"
export GTK_PATH="$bundle_res"

export GTK2_RC_FILES="$bundle_etc/gtk-2.0/gtkrc"
export GTK_IM_MODULE_FILE="$bundle_etc/gtk-2.0/gtk.immodules"
export GDK_PIXBUF_MODULE_FILE="$bundle_etc/gtk-2.0/gdk-pixbuf.loaders"
export PANGO_RC_FILE="$bundle_etc/pango/pangorc"

#Set $PYTHON to point inside the bundle
#This is not the real "python" but a copy of it named "xpra"
#This is hacked together in make-app.sh
export PYTHON="$bundle_bin/Xpra"
export PYTHONHOME="$bundle_res"
#Add the bundle's python modules
PYTHONPATH="$bundle_lib:$PYTHONPATH"
PYTHONPATH="$bundle_lib/python/lib-dynload/:$PYTHONPATH"
PYTHONPATH="$bundle_lib/python/:$PYTHONPATH"
PYTHONPATH="$bundle_lib/pygtk/2.0:$PYTHONPATH"
export PYTHONPATH

# We need a UTF-8 locale.
lang=`defaults read .GlobalPreferences AppleLocale 2>/dev/null`
if test "$?" != "0"; then
	lang=`defaults read .GlobalPreferences AppleCollationOrder 2>/dev/null | sed 's/_.*//'`
fi
LANG=""
if test "$lang" != ""; then
	LANG="`grep \"\`echo $lang\`_\" /usr/share/locale/locale.alias | \
		tail -n1 | sed 's/\./ /' | awk '{print $2}'`"
fi
if test "$LANG" == ""; then
	export LANG="C"
else
	export LANG="$LANG.utf8"
fi

if test -f "$bundle_lib/charset.alias"; then
    export CHARSETALIASDIR="$bundle_lib"
fi

# Extra arguments can be added in environment.sh.
EXTRA_ARGS=
if test -f "$bundle_res/environment.sh"; then
  source "$bundle_res/environment.sh"
fi


args="[\"xpra\""
while (($#)); do
    args="$args,\"$1\""
    shift
done
args="$args]"

exec $PYTHON -c "import sys;sys.argv[0]=\"$full_path\";from xpra.scripts.client_launcher import main;main()"
