#!/usr/bin/env python3
# This file is part of Xpra.
# Copyright (C) 2026 Antoine Martin <antoine@xpra.org>
# Xpra is released under the terms of the GNU GPL v2, or, at your option, any
# later version. See the file COPYING for details.

"""
Keymap diagnostic tool.

`xpra keymap` dumps the keyboard data that this client would send to a server,
`xpra keymap-test` takes such a dump and applies it to an X11 display exactly
as a server would, then verifies that every key the client claims to have
can actually be generated by the server.

This makes it possible to diagnose keyboard mapping issues from any client
platform without having to run that client: ask the user to send the output of
`xpra keymap`, see #4963.
"""

import json
import os
import sys
from collections.abc import Iterable, Sequence
from typing import Any

from xpra.util.objects import typedict
from xpra.util.str_fn import csv

# the keysyms used to reach the third and fourth level of a group,
# ie: `AltGr` on a German keyboard:
LEVEL3_KEYNAMES = ("ISO_Level3_Shift", "Mode_switch")


def init_x11_display() -> None:
    """ the X11 bindings need a display connection of their own """
    from xpra.x11.bindings.display_source import init_display_source
    init_display_source()


def get_local_keymap() -> dict[str, Any]:
    """ the keyboard data this client would send to a server """
    from xpra.util.system import is_X11
    if is_X11():
        init_x11_display()
    from xpra.client.gtk3.keyboard_helper import GTKKeyboardHelper

    def noop(*_args) -> None:
        """ this keyboard helper is not connected to a server """

    helper = GTKKeyboardHelper(noop)
    try:
        helper.query_xkbmap()
        return helper.get_keymap_properties()
    finally:
        helper.cleanup()


def load_keymap(filename: str) -> dict[str, Any]:
    with open(filename, "r", encoding="utf8") as f:
        keymap = json.load(f)
    if not isinstance(keymap, dict):
        raise ValueError(f"{filename!r} does not contain a keymap dictionary")
    # json object keys are always strings,
    # but `x11_keycodes` is indexed by keycode:
    x11_keycodes = keymap.get("x11_keycodes")
    if isinstance(x11_keycodes, dict):
        keymap["x11_keycodes"] = {int(keycode): keysyms for keycode, keysyms in x11_keycodes.items()}
    # and the keycode definitions are tuples, not lists:
    keycodes = keymap.get("keycodes")
    if keycodes:
        keymap["keycodes"] = tuple(tuple(kdef) for kdef in keycodes)
    return keymap


def find_level3_modifier(mod_meanings: dict[str, str]) -> str:
    """ the modifier the *client* uses to reach the third level, ie: `mod5` """
    for keyname, modifier in mod_meanings.items():
        if keyname in LEVEL3_KEYNAMES:
            return modifier
    return "mod5"


def is_level3(keynames: Iterable[str]) -> bool:
    return bool(set(keynames) & set(LEVEL3_KEYNAMES))


def keysym_at_level(keysyms: Sequence[str], level: int) -> str:
    """
    which keysym the X11 server generates at the given level,
    xpra uses 4 levels for each layout group (see `get_levels`),
    and the X11 server falls back to the lower levels of the same group
    when a level is not mapped
    """
    group = (level // 4) * 4
    for lvl in (level, level - 2, group):
        if group <= lvl < len(keysyms) and keysyms[lvl]:
            return keysyms[lvl]
    return ""


def check_keymap(keymap: dict[str, Any], keysyms: Sequence[str] = ()) -> tuple[int, int]:
    """
    Configure the keyboard using this client keymap,
    then verify that each key the client has can be generated,
    returns how many keys were checked and how many of those cannot be generated.
    """
    from xpra.x11.bindings.keyboard import X11KeyboardBindings
    from xpra.x11.server.keyboard_config import KeyboardConfig
    from xpra.x11.xkbhelper import get_keycode_mappings
    X11Keyboard = X11KeyboardBindings()
    config = KeyboardConfig()
    # the same calls the server makes when a client connects,
    # using the same 'keymap' sub-dictionary as the hello packet:
    props = typedict({"keymap": keymap})
    config.parse_options(props)
    config.parse_layout(props)
    config.set_keymap()
    print(f"keyboard config: {config}")
    print(" %i client keycode definitions, %i translation entries" % (
        len(config.keycodes or ()), len(config.keycode_translation)))
    print(" modifiers: %s" % csv("%s=%s" % (mod, csv(keynames))
                                 for mod, keynames in config.keynames_for_mod.items()))
    if not config.keycodes:
        print("Warning: this keymap does not contain any keycode definitions")
        if keymap.get("x11_keycodes"):
            print(" (only the native x11 keycodes, which are used as-is)")
        return 0, 0

    mappings = get_keycode_mappings()
    client_level3 = find_level3_modifier(typedict(keymap).dictget("mod_meanings") or {})
    kdefs = tuple(kdef for kdef in config.keycodes if not keysyms or kdef[1] in keysyms)
    if keysyms and not kdefs:
        print(f"Warning: this keymap does not have any key matching {csv(keysyms)}")
        return 0, 0
    checking = f"{len(kdefs)} of the {len(config.keycodes)}" if keysyms else str(len(config.keycodes))
    print(f"checking {checking} keys against the {config.layout!r} layout:")
    failures = 0
    unsupported = []
    for kdef in kdefs:
        keyval, keyname, client_keycode, group, level = kdef
        if level > 3:
            # ie: `ISO_Level5_Shift` combinations, which we cannot map
            unsupported.append(keyname)
            continue
        # the modifiers the client holds down to reach this key:
        modifiers = []
        if level & 1:
            modifiers.append("shift")
        if level & 2:
            modifiers.append(client_level3)
        # `get_keycode` modifies the modifiers to match the key it has found,
        # and caches the translation for the key release - which we don't send:
        config.pressed_translation = {}
        keycode, rgroup = config.get_keycode(client_keycode, keyname, True, modifiers, keyval, "", group)
        keysyms_for_keycode = mappings.get(keycode, ())
        server_level = 4 * rgroup + int("shift" in modifiers)
        if any(is_level3(config.keynames_for_mod.get(mod, ())) for mod in modifiers):
            server_level += 2
        produced = keysym_at_level(keysyms_for_keycode, server_level)
        # some clients use their own keysym names (ie: gtk drops the `XF86` prefix)
        # so compare the keyvals rather than the names when we can:
        if produced == keyname or (produced and keyval and X11Keyboard.parse_keysym(produced) == keyval):
            continue
        failures += 1
        if keycode <= 0:
            print(f" {keyname!r} (client keycode {client_keycode}, group {group}, level {level})"
                  " is not mapped on the server")
            continue
        print(f" {keyname!r} (client keycode {client_keycode}, group {group}, level {level})"
              f" -> keycode {keycode} {csv(modifiers) or 'without any modifiers'}"
              f" (group {rgroup}, level {server_level}) which generates {produced!r}")
        print(f"    keycode {keycode} is mapped to: {csv(keysyms_for_keycode)}")
    if unsupported:
        print(f" ({len(unsupported)} keys use more than 4 levels and cannot be checked: {csv(unsupported)})")
    return len(kdefs) - len(unsupported), failures


def start_vfb() -> tuple[Any, str]:
    """ start a throwaway X11 server so we don't modify the keymap of a real display """
    import subprocess
    from xpra.platform.displayfd import read_displayfd, parse_displayfd
    r_pipe, w_pipe = os.pipe()
    cmd = ["Xvfb", "-displayfd", str(w_pipe), "-screen", "0", "640x480x24", "-nolisten", "tcp"]
    try:
        # (`-displayfd` prints errors for all the display numbers already in use)
        proc = subprocess.Popen(cmd, pass_fds=(w_pipe,),
                                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except OSError as e:
        raise RuntimeError(f"failed to execute {cmd[0]!r}: {e}, please specify a display to use") from None
    os.close(w_pipe)
    buf = read_displayfd(r_pipe, proc=proc)
    os.close(r_pipe)

    def displayfd_err(msg: str) -> None:
        proc.terminate()
        raise RuntimeError(f"failed to start {cmd[0]!r}: {msg}")

    n = parse_displayfd(buf, displayfd_err)
    return proc, f":{n}"


def dumps(keymap: dict[str, Any]) -> str:
    """ json, with the innermost values kept on a single line so the dump remains readable """

    def entries(values: Iterable[str]) -> str:
        return "\n".join(f"        {value}," for value in values).rstrip(",")

    lines = []
    for key in sorted(keymap.keys()):
        value = keymap[key]
        if isinstance(value, dict):
            body = entries(f"{json.dumps(str(k))}: {json.dumps(v, default=str)}" for k, v in value.items())
            lines.append('    %s: {\n%s\n    }' % (json.dumps(key), body))
        elif isinstance(value, (list, tuple)):
            body = entries(json.dumps(v, default=str) for v in value)
            lines.append('    %s: [\n%s\n    ]' % (json.dumps(key), body))
        else:
            lines.append("    %s: %s" % (json.dumps(key), json.dumps(value, default=str)))
    return "{\n%s\n}" % ",\n".join(lines)


def dump(args: list[str]) -> int:
    keymap = get_local_keymap()
    out = dumps(keymap)
    if args and not args[0].startswith("-"):
        filename = args[0]
        with open(filename, "w", encoding="utf8") as f:
            f.write(out + "\n")
        print(f"keymap saved to {filename!r}")
    else:
        print(out)
    return 0


def test(args: list[str]) -> int:
    display = ""
    filename = ""
    keysyms = []
    for arg in args:
        if arg.startswith("-"):
            continue
        if arg.startswith(":"):
            display = arg
        elif not filename and os.path.isfile(arg):
            filename = arg
        elif arg.endswith(".json") or os.path.sep in arg:
            raise ValueError(f"{arg!r} is not a file")
        else:
            keysyms.append(arg)
    keymap = load_keymap(filename) if filename else get_local_keymap()
    print("using the keymap from %s" % (f"{filename!r}" if filename else "this system"))

    vfb = None
    if display:
        print(f"Warning: the keymap of display {display!r} will be modified")
    else:
        vfb, display = start_vfb()
        print(f"started {display!r}")
    try:
        os.environ["DISPLAY"] = display
        init_x11_display()
        checked, failures = check_keymap(keymap, tuple(keysyms))
    finally:
        if vfb:
            vfb.terminate()
            vfb.wait()
    if failures:
        print("%i key%s out of %i cannot be generated by the server" % (
            failures, "s" if failures > 1 else "", checked))
        return 1
    if not checked:
        return 1
    print(f"all {checked} keys can be generated by the server")
    return 0


def main(mode: str, args: list[str], cmdline: list[str]) -> int:
    from xpra.platform import program_context
    from xpra.log import enable_color, consume_verbose_argv
    with program_context("Keymap-Tool", "Keymap Tool"):
        enable_color()
        consume_verbose_argv(cmdline, "keyboard")
        if mode == "keymap":
            return dump(args)
        return test(args)


if __name__ == "__main__":  # pragma: no cover
    # ie: `python3 -m xpra.scripts.keymap_tool keymap-test keymap.json`
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "keymap", sys.argv[2:], sys.argv))
