#!/bin/sh

#call the "Python" wrapper:
exe_name=$(basename $0)
full_path=$(cd "$(dirname "$0")"; pwd -P)
PYTHON="$full_path/PythonExecWrapper"

exec "$PYTHON" "Xpra" -c "import sys;sys.argv[0]=\"${full_path}/$exe_name\";from xpra.client.gtk_base.mdns_gui import main;main()" "$@"
