.TH PARTI "1" "December 2010" "" "User Commands"
.SH NAME
parti \- tabbing/tiling window manager using GTK+
.PP
parti-repl \- spawn REPL window in the running Parti session
.SH SYNOPSIS
.B parti
[\fI--replace\fR] [\fI-h\fR, \fI--help\fR] [\fI--version\fR]
.PP
.B parti-repl
.SH DESCRIPTION
\fBparti\fP is a tabbing/tiling (one might say "partitioning") window manager.
Its goal is to bring this superior window management interface to modern,
mainstream desktop environments.
.PP
\fBparti-repl\fP is a script that uses D-Bus to request the running Parti spawn
a REPL window.

.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-replace\fR
Replace any running window manager with Parti
.SH AUTHOR
parti was written by Nathaniel Smith <njs@pobox.com>.
.PP
This manual page was written by أحمد المحمودي (Ahmed El-Mahmoudy) <aelmahmoudy@sabily.org>,
for the Debian project (and may be used by others).
