#!/usr/bin/bash

export XPRA_UTIL_DEBUG=1
export XPRA_TEST_DEBUG=1
export XPRA_HIDE_SUBPROCESS_OUTPUT=0
#SAVED_PYTHONPATH=$PYTHONPATH

python2 ./setup.py install --home=./install/python2
export PYTHONPATH=`pwd`/`ls -d ./install/python2/lib*/python`:.
export PATH=`pwd`/install/python2/bin:$PATH
export XPRA_COMMAND=`pwd`/install/python2/bin/xpra
export XPRA_CONF_DIR=`pwd`/install/python2/etc/xpra/

python2 ./unit/run.py
