#!/usr/bin/bash

export XPRA_UTIL_DEBUG=1
export XPRA_TEST_DEBUG=1
export XPRA_HIDE_SUBPROCESS_OUTPUT=0
#SAVED_PYTHONPATH=$PYTHONPATH

python3 ./setup.py install --home=./install/python3
export PYTHONPATH=`pwd`/`ls -d ./install/python3/lib*/python`:.
export PATH=`pwd`/install/python3/bin:$PATH
export XPRA_COMMAND=`pwd`/install/python3/bin/xpra
export XPRA_CONF_DIR=`pwd`/install/python3/etc/xpra/

python3 ./unit/run.py
