#!/usr/bin/env python

import sys
import xpra.scripts.main

import cProfile


def main() -> int:
    return xpra.scripts.main.do_main(__file__, sys.argv)


cProfile.run("main()", "profile.stats")


import pstats
p = pstats.Stats("profile.stats")

p.sort_stats('time').print_stats()
