#!/usr/bin/env python

import sys
import xpra.scripts.main

import cProfile
def main():
	xpra.scripts.main.main(__file__, sys.argv)

cProfile.run("main()", "profile.stats")

import pstats
p = pstats.Stats("profile.stats")

p.sort_stats('time').print_stats()
